openapi: 3.0.1
info:
  title: Storytime
  description: "This is the openAPI spec for the the [Storytime](https://storytime.com) backend."
  contact:
    email: info@storytime.com
  version: 1.0.0
servers:
  - url: http://storytime.com/api/v1
  - url: https://storytime.com/api/v1

tags:
  - name: auth
    description: Authentication and account recovery endpoints

paths:
  /signup:
    post:
      tags:
        - auth
      summary: Register a new account
      description: Register a new account
      requestBody:
        description: Create new storytime user account
        required: true
        content:
          application/json:
            schema:
              $ref: "request-spec.yml#/components/schemas/NewUser"
      responses:
        "201":
          description: Account created
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/UserDetails"
        "422":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/ValidationError"

  /verify/{token}:
    get:
      tags:
        - auth
      summary: Verify email address
      description: Email verification endpoint
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
        - in: query
          name: signature
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Email address verified
        "400":
          description: Invalid url signature
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/BadRequestError"
        "404":
          description: Token not found
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/NotFoundError"

  /resend_verification/:email:
    get:
      tags:
        - auth
      summary: Resend verification email to user
      description: Resendd verification email to user
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Verification email resent
        "404":
          description: Provided email not found
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/NotFoundError"

  /forgot_password/:email:
    get:
      tags:
        - auth
      summary: Get password reset token
      description: Get password reset url delivered to mail
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Reset url sent to user's email
        "404":
          description: Provided email not found
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/NotFoundError"

  /reset_password/{token}:
    post:
      tags:
        - auth
      summary: Reset password
      description: Reset password
      requestBody:
        description: Password reset payload
        required: true
        content:
          application/json:
            schema:
              $ref: "request-spec.yml#/components/schemas/PasswordReset"
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
        - in: query
          name: signature
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Password reset successfully
        "400":
          description: Invalid reset url
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/BadRequestError"
        "404":
          description: Token not found
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/NotFoundError"

  /login:
    post:
      tags:
        - auth
      summary: Login
      description: Login
      requestBody:
        description: login payload
        required: true
        content:
          application/json:
            schema:
              $ref: "request-spec.yml#/components/schemas/LoginDetails"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/LoginTokenDetails"
        "422":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/ValidationError"
        "400":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/BadRequestError"

  /logout:
    get:
      tags:
        - auth
      summary: Logout
      description: Logout
      responses:
        "204":
          description: Logout successful
        "401":
          description: Unauthorised logout
          content:
            application/json:
              schema:
                $ref: "response-spec.yml#/components/schemas/UnauthorizedAccessError"
